import React,{useEffect,useState} from 'react';
import Modal from './components/Modal.jsx';
import Select from './components/Select.jsx';
export default function Accounts({request,notify}){
 const [accounts,setAccounts]=useState([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[name,setName]=useState(''),[broker,setBroker]=useState('ibkr'),[saving,setSaving]=useState(false);
 const [loadError,setLoadError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoadError('');setLoaded(false);fetch('/api/accounts/',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error(`Could not load accounts (HTTP ${r.status}).`);const d=await r.json();if(!Array.isArray(d.accounts))throw Error('The accounts response was invalid.');return d}).then(d=>{setAccounts(d.accounts);setLoaded(true)}).catch(e=>{if(e.name!=='AbortError')setLoadError(e.message==='Failed to fetch'?'Could not reach the server to load accounts.':e.message)});return()=>c.abort()},[attempt]);

 async function save(e){e.preventDefault();setSaving(true);setError('');try{const account=await request('/api/accounts/','POST',{name,broker});setAccounts(old=>[...old,account]);setOpen(false);notify('Brokerage account added.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <section className="panel"><div className="panel-heading"><h2>Accounts <span className="subtle">{accounts.length} / 10</span></h2><button className="primary" disabled={!loaded||accounts.length>=10} onClick={()=>{setName('');setBroker('ibkr');setError('');setOpen(true)}}>＋ Add account</button></div>{loadError&&<div role="alert" className="alert error">{loadError} <button onClick={()=>setAttempt(n=>n+1)}>Retry</button></div>}{!loaded&&!loadError?<p role="status">Loading accounts…</p>:loaded&&!accounts.length?<div className="empty">No brokerage accounts yet.</div>:loaded?<div className="strategy-table-scroll"><table className="strategy-table account-table"><thead><tr>{['Account name','Broker','Profit calculation','Last import','Import method'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><strong>{a.name}</strong></td><td><span className={`broker-pill broker-${a.broker}`}>{a.broker_name}</span></td><td>FIFO</td><td>{a.last_import_at?new Date(a.last_import_at).toLocaleString():'—'}</td><td>{a.broker==='ibkr'?'CSV upload':'thinkorswim CSV'}</td></tr>)}</tbody></table></div>:null}{open&&<Modal title="Add brokerage account" busy={saving} onClose={()=>setOpen(false)}><form className="profile-form" onSubmit={save}><label>Account name<input autoFocus required maxLength={100} disabled={saving} value={name} onChange={e=>setName(e.target.value)}/></label><label>Broker<Select disabled={saving} value={broker} onChange={e=>setBroker(e.target.value)}><option value="ibkr">Interactive Brokers</option><option value="schwab">Charles Schwab</option></Select></label>{error&&<p role="alert" className="alert error">{error}</p>}<button className="primary" disabled={saving}>{saving?'Adding…':'Add account'}</button></form></Modal>}</section>
}
