import {useAccount} from './AccountScope.jsx';
import React,{useEffect,useRef,useState} from 'react';
import Modal from './components/Modal.jsx';
import Popover from './components/Popover.jsx';
import Select from './components/Select.jsx';

function AccountMenu({account,onAction,disabled}){
 const anchor=useRef(null),[open,setOpen]=useState(false);
 return <><button ref={anchor} type="button" className="strategy-menu-trigger" aria-label={`Actions for ${account.name}`} aria-expanded={open} disabled={disabled} onClick={()=>setOpen(!open)}>⋮</button>{open&&<Popover anchor={anchor} label="Account actions" className="strategy-mini-menu" onClose={()=>setOpen(false)}>{[['edit','Edit'],['clear','Clear data'],['delete','Delete']].map(([action,label])=><button key={action} type="button" onClick={()=>{setOpen(false);onAction(action,account)}}>{label}</button>)}</Popover>}</>;
}
export default function Accounts({request,notify,onAccountDataAction}){
 const {refreshAccounts}=useAccount();
 const [accounts,setAccounts]=useState([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[confirmation,setConfirmation]=useState(null),[name,setName]=useState(''),[broker,setBroker]=useState('ibkr'),[saving,setSaving]=useState(false);
 const [loadError,setLoadError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoadError('');setLoaded(false);fetch('/api/accounts/',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error(`Could not load accounts (HTTP ${r.status}).`);const d=await r.json();if(!Array.isArray(d.accounts))throw Error('The accounts response was invalid.');return d}).then(d=>{setAccounts(d.accounts);setLoaded(true)}).catch(e=>{if(e.name!=='AbortError')setLoadError(e.message)});return()=>c.abort()},[attempt]);
 function action(kind,account){setError('');if(kind==='edit'){setEditing(account);setName(account.name);setBroker(account.broker);setOpen(true)}else setConfirmation({kind,account})}
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const account=await request(editing?`/api/accounts/${editing.id}/`:'/api/accounts/',editing?'PUT':'POST',{name,broker});setAccounts(old=>editing?old.map(a=>a.id===account.id?account:a):[...old,account]);await refreshAccounts();setOpen(false);notify(editing?'Account updated.':'Brokerage account added.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function confirm(){setSaving(true);setError('');try{const {kind,account}=confirmation;const result=await onAccountDataAction(account.id,kind);if(result.pending_files){setError('Trading data was cleared, but some attachment files could not be removed. Try again to finish.');setAttempt(n=>n+1);return}setConfirmation(null);setAttempt(n=>n+1);notify(kind==='delete'?'Account deleted.':`Trading data cleared for ${account.name}.`)}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <section className="panel"><div className="panel-heading"><h2>Accounts <span className="subtle">{accounts.length} / 10</span></h2><button className="primary" disabled={!loaded||saving||accounts.length>=10} onClick={()=>{setEditing(null);setName('');setBroker('ibkr');setError('');setOpen(true)}}>＋ Add account</button></div>{loadError&&<div role="alert" className="alert error">{loadError} <button onClick={()=>setAttempt(n=>n+1)}>Retry</button></div>}{!loaded&&!loadError?<p role="status">Loading accounts…</p>:loaded&&!accounts.length?<div className="empty">No brokerage accounts yet.</div>:loaded?<div className="strategy-table-scroll"><table className="strategy-table account-table"><thead><tr>{['Account name','Broker','Profit calculation','Last import','Import method','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><strong>{a.name}</strong></td><td><span className={`broker-pill broker-${a.broker}`}>{a.broker_name}</span></td><td>FIFO</td><td>{a.last_import_at?new Date(a.last_import_at).toLocaleString():'—'}</td><td>{a.broker==='schwab'?'thinkorswim CSV':a.broker==='tradovate'?'Tradovate CSV':'CSV upload'}</td><td><AccountMenu account={a} onAction={action} disabled={saving}/></td></tr>)}</tbody></table></div>:null}
 {open&&<Modal title={editing?'Edit brokerage account':'Add brokerage account'} busy={saving} onClose={()=>setOpen(false)}><form className="profile-form" onSubmit={save}><label>Account name<input autoFocus required maxLength={100} disabled={saving} value={name} onChange={e=>setName(e.target.value)}/></label><label>Broker<Select disabled={saving||editing?.broker_locked} value={broker} onChange={e=>setBroker(e.target.value)}><option value="ibkr">Interactive Brokers</option><option value="schwab">Charles Schwab</option><option value="tradovate">Tradovate</option></Select></label>{error&&<p role="alert" className="alert error">{error}</p>}<button className="primary" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Add account'}</button></form></Modal>}
 {confirmation&&<Modal title={confirmation.kind==='delete'?'Delete account?':'Clear account data?'} busy={saving} onClose={()=>setConfirmation(null)}><p>{confirmation.kind==='delete'?'Delete':'Clear all trading data for'} <strong>{confirmation.account.name}</strong>? {confirmation.kind==='delete'?'This removes the account and all its':'This permanently removes its'} executions, trades, daily plans and reviews, journal notes, and attachments.</p><p>Other accounts, your profile, rules, and strategy definitions will be kept. <strong>This cannot be undone.</strong></p>{error&&<p className="alert error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" autoFocus disabled={saving} onClick={()=>setConfirmation(null)}>Cancel</button><button type="button" className="danger-button" disabled={saving} onClick={confirm}>{saving?'Working…':confirmation.kind==='delete'?'Delete account':'Clear account data'}</button></div></Modal>}
 </section>;
}
