import React,{useState} from 'react';
import Modal from './components/Modal.jsx';
import TrashButton from './components/TrashButton.jsx';
export default function ExecutionList({executions,request,onUpdated,notify,beforeDelete}){
 const [selected,setSelected]=useState([]),[removing,setRemoving]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function remove(){setBusy(true);setError('');try{if(beforeDelete&&!await beforeDelete()){setError('Save the trade journal before deleting executions.');return}const result=await request('/api/executions/delete/','DELETE',{ids:removing});await onUpdated(result);setSelected([]);setRemoving(null);notify(result.pending_files?'Executions deleted; some attachment files could not be removed.':`${result.deleted} executions deleted.`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const ids=executions.map(r=>r.trade_id);
 return <section className="execution-management"><div className="selection-toolbar"><h3>Executions</h3>{selected.length>0&&<button className="danger-button" disabled={busy} onClick={()=>setRemoving(selected)}>Delete selected ({selected.length})</button>}</div>{executions.length>0&&<label className="execution-select-all"><input type="checkbox" disabled={busy} checked={ids.every(id=>selected.includes(id))} onChange={e=>setSelected(e.target.checked?ids:[])}/>Select all</label>}<div className="execution-table-wrap"><table className="execution-table"><thead><tr><th/><th>Time</th><th>Ticker</th><th>Action</th><th>Quantity</th><th>Price</th><th/></tr></thead><tbody>{executions.map(r=><tr key={r.trade_id}><td><input type="checkbox" disabled={busy} aria-label={`Select execution ${r.trade_id}`} checked={selected.includes(r.trade_id)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.trade_id]:s.filter(id=>id!==r.trade_id))}/></td><td>{r.execution_time}</td><td><span className="ticker-pill">{r.symbol}</span></td><td>{r.side==='BUY'?'Buy':'Sell'}</td><td>{Number(r.quantity)}</td><td>{Number(r.price).toLocaleString('en-US',{maximumFractionDigits:6})}</td><td><TrashButton label={`Delete execution ${r.trade_id}`} disabled={busy} onClick={()=>{setError('');setRemoving([r.trade_id])}}/></td></tr>)}</tbody></table></div>{removing&&<Modal title="Delete executions?" busy={busy} onClose={()=>setRemoving(null)}><p>Permanently delete {removing.length} execution{removing.length===1?'':'s'}? Trade quantities and P&L will be recalculated. If all executions of a trade are removed, its journal and attachments will also be deleted. This cannot be undone.</p>{error&&<p className="alert error" role="alert">{error}</p>}<div className="modal-actions"><button autoFocus disabled={busy} onClick={()=>setRemoving(null)}>Cancel</button><button className="danger-button" disabled={busy} onClick={remove}>{busy?'Deleting…':'Delete'}</button></div></Modal>}</section>
}
