import React,{useState} from 'react';
import Modal from './components/Modal.jsx';
import TrashButton from './components/TrashButton.jsx';
export default function Rulebook({rules,request,onUpdated,notify}){
 const [editing,setEditing]=useState(null),[draft,setDraft]=useState({text:'',weight:1}),[adding,setAdding]=useState(false),[selection,setSelection]=useState([]),[removing,setRemoving]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [dragged,setDragged]=useState(null),[over,setOver]=useState(null);
 async function move(source,target){if(controlsLocked||source===target||source===null)return;const ids=rules.map(r=>r.id);ids.splice(ids.indexOf(source),1);ids.splice(rules.findIndex(r=>r.id===target),0,source);setBusy(true);setError('');try{const result=await request('/api/rules/reorder/','POST',{ids});onUpdated(result.rules,result.rule_order);notify('Rule order saved.')}catch(e){setError(e.message)}finally{setBusy(false);setDragged(null);setOver(null)}}
 const editingRule=editing!==null||adding;
 const controlsLocked=busy||editingRule;
 const toggle=id=>setSelection(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 function edit(r){if(controlsLocked)return;setEditing(r.id);setDraft({...r});setAdding(false);setError('')}
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=await request('/api/rules/','POST',draft);onUpdated(editing===null?[...rules,result]:rules.map(r=>r.id===editing?result:r));setEditing(null);setAdding(false);setSelection(s=>s.filter(id=>id!==editing));notify('Rule saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(){setBusy(true);setError('');try{const result=await request('/api/rules/delete/','DELETE',{ids:removing});onUpdated(result.rules);setSelection([]);if(removing.includes(editing))setEditing(null);setRemoving(null);notify('Rules deleted.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const form=<form className="inline-rule-form" onSubmit={save}><label>Rule<textarea autoFocus disabled={busy} required maxLength="300" rows="3" value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><label>Importance (1–10)<input disabled={busy} required type="number" min="1" max="10" value={draft.weight} onChange={e=>setDraft({...draft,weight:Number(e.target.value)})}/></label><div className="inline-actions"><button className="primary" disabled={busy}>Save</button><button type="button" disabled={busy} onClick={()=>{setEditing(null);setAdding(false);setError('')}}>Cancel</button></div></form>;
 return <section className="panel rulebook-panel"><div className="panel-heading"><h2>Trading rules</h2><button disabled={controlsLocked} onClick={()=>{setEditing(null);setAdding(true);setDraft({text:'',weight:1});setError('')}}>Add rule</button></div>{error&&!removing&&<p className="alert error" role="alert">{error}</p>}{rules.length>0&&<div className="selection-toolbar"><label><input type="checkbox" checked={selection.length===rules.length} disabled={controlsLocked} onChange={e=>setSelection(e.target.checked?rules.map(r=>r.id):[])}/>Select all</label>{selection.length>0&&<button className="danger-button" disabled={controlsLocked} onClick={()=>{setError('');setRemoving(selection)}}>Delete selected ({selection.length})</button>}</div>}{rules.map(r=><div className={`editable-rule-row${over===r.id?' rule-drop-target':''}`} key={r.id} onDragOver={e=>{if(!controlsLocked&&dragged!==null){e.preventDefault();setOver(r.id)}}} onDrop={e=>{e.preventDefault();move(dragged,r.id)}}><button type="button" className="rule-drag-handle" disabled={controlsLocked||rules.length<2} draggable={!controlsLocked} aria-label={`Reorder rule: ${r.text}`} title="Drag to reorder; use arrow keys to move" onDragStart={e=>{setDragged(r.id);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(r.id))}} onDragEnd={()=>{setDragged(null);setOver(null)}} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();const target=rules[rules.indexOf(r)+(e.key==='ArrowUp'?-1:1)];if(target)move(r.id,target.id)}}}><svg viewBox="0 0 24 24" aria-hidden="true">{[6,12,18].flatMap(y=>[9,15].map(x=><circle key={`${x}-${y}`} cx={x} cy={y} r="1.5"/>))}</svg></button><input type="checkbox" aria-label={`Select rule: ${r.text}`} checked={selection.includes(r.id)} disabled={controlsLocked} onChange={()=>toggle(r.id)}/>{editing===r.id?form:<><div className="editable-rule-content"><strong>{r.text}</strong><small>Weight {r.weight}</small></div><div className="inline-actions"><button disabled={controlsLocked} onClick={()=>edit(r)}>Edit</button><TrashButton label={`Delete rule: ${r.text}`} disabled={controlsLocked} onClick={()=>{setError('');setRemoving([r.id])}}/></div></>}</div>)}{adding&&form}{removing&&<Modal title={removing.length===1?'Delete rule?':'Delete selected rules?'} busy={busy} onClose={()=>setRemoving(null)}><p>Delete {removing.length===1?'this rule':`these ${removing.length} rules`} from your rulebook? Saved daily reviews will keep their original rules.</p>{error&&<p className="alert error" role="alert">{error}</p>}<div className="modal-actions"><button autoFocus disabled={busy} onClick={()=>setRemoving(null)}>Cancel</button><button className="danger-button" disabled={busy} onClick={remove}>{busy?'Deleting…':'Delete'}</button></div></Modal>}</section>
}
