import Accounts from './Accounts.jsx';
import React,{useEffect,useState} from 'react';
import {useAccountViewState} from './AccountScope.jsx';
export default function Settings({request,notify,onAccountDataAction,photoUrl,onPhoto,csrfToken}){
 const [savedTab,setTab]=useAccountViewState('settings-tab','Profile');
 const tab=savedTab==='Accounts'?'Accounts':'Profile';
 const [profile,setProfile]=useState({display_name:'',bio:''}),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/profile/',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Could not load your profile.');return r.json()}).then(p=>{setProfile(p);setLoaded(true)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[]);
 async function save(e){e.preventDefault();setSaving(true);setError('');try{setProfile(await request('/api/profile/','PUT',profile));notify('Profile saved.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function updatePhoto(file){setSaving(true);setError('');try{const body=new FormData();if(file)body.append('photo',file);const response=await fetch('/api/profile/photo/',{method:file?'POST':'DELETE',headers:{'X-CSRFToken':csrfToken},...(file?{body}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'Could not update photo.');onPhoto(result.photo_url);notify(file?'Profile photo saved.':'Profile photo removed.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className={`settings-view ${tab==='Accounts'?'accounts-settings':''}`}><div className="trade-detail-tabs" role="tablist" aria-label="Settings">{['Profile','Accounts'].map(name=><button key={name} role="tab" aria-selected={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</div>{tab==='Accounts'?<Accounts request={request} notify={notify} onAccountDataAction={onAccountDataAction}/>:<><section className="panel"><div className="panel-heading"><h2>Profile</h2><span className="profile-avatar" aria-hidden="true">{photoUrl?<img src={photoUrl} alt="Profile"/>:profile.display_name.trim().slice(0,1).toUpperCase()||'✓'}</span></div><form onSubmit={save} className="profile-form"><label>Profile photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={saving} onChange={e=>{if(e.target.files[0])updatePhoto(e.target.files[0]);e.target.value=''}}/></label>{photoUrl&&<button type="button" disabled={saving} onClick={()=>updatePhoto(null)}>Remove photo</button>}<label>Display name<input maxLength="100" autoComplete="name" value={profile.display_name} disabled={!loaded||saving} onChange={e=>setProfile({...profile,display_name:e.target.value})}/></label><label>About you<textarea rows="4" maxLength="1000" value={profile.bio} disabled={!loaded||saving} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label>{error&&<p className="alert error" role="alert">{error}</p>}<button className="primary" disabled={!loaded||saving}>{saving?'Saving…':'Save profile'}</button></form></section></>}
 </div>
}
