import Accounts from './Accounts.jsx';
import React,{useEffect,useState} from 'react';
import Modal from './components/Modal.jsx';
export default function Settings({request,notify,onClear}){
 const [tab,setTab]=useState('Profile');
 const [profile,setProfile]=useState({display_name:'',bio:''}),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[clearing,setClearing]=useState(false),[clearError,setClearError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/profile/',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Could not load your profile.');return r.json()}).then(p=>{setProfile(p);setLoaded(true)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[]);
 async function save(e){e.preventDefault();setSaving(true);setError('');try{setProfile(await request('/api/profile/','PUT',profile));notify('Profile saved.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function clear(){setClearing(true);setClearError('');try{const result=await onClear();setConfirm(false);if(result.pending_files)setClearError('Trading and journal records were cleared, but some attachment files could not be removed. Choose Clear all trade and journal data again to retry.');else notify('All trade and journal data cleared.')}catch(e){setClearError(e.message)}finally{setClearing(false)}}
 return <div className="settings-view"><div className="trade-detail-tabs" role="tablist" aria-label="Settings">{['Profile','Accounts'].map(name=><button key={name} role="tab" aria-selected={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</div>{tab==='Accounts'?<Accounts request={request} notify={notify}/>:<><section className="panel"><div className="panel-heading"><h2>Profile</h2><span className="profile-avatar" aria-hidden="true">{profile.display_name.trim().slice(0,1).toUpperCase()||'✓'}</span></div><form onSubmit={save} className="profile-form"><label>Display name<input maxLength="100" autoComplete="name" value={profile.display_name} disabled={!loaded||saving} onChange={e=>setProfile({...profile,display_name:e.target.value})}/></label><label>About you<textarea rows="4" maxLength="1000" value={profile.bio} disabled={!loaded||saving} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label>{error&&<p className="alert error" role="alert">{error}</p>}<button className="primary" disabled={!loaded||saving}>{saving?'Saving…':'Save profile'}</button></form></section><section className="panel danger-zone"><div className="panel-heading"><h2>Clear trading data</h2></div><button className="danger-button" onClick={()=>{setClearError('');setConfirm(true)}}>Clear all trade and journal data</button>{clearError&&!confirm&&<p className="alert error" role="alert">{clearError}</p>}</section></>}
 {confirm&&<Modal title="Clear all trade and journal data?" className="clear-data-modal" onClose={()=>setConfirm(false)} busy={clearing}><p>This permanently deletes all trades and executions, daily plans and reviews, journal entries, and session and trade attachments. Grades and your consistency streak will reset.</p><p>Your profile, rulebook, and theme will be kept.</p><p><strong>This cannot be undone.</strong></p>{clearError&&<p className="alert error" role="alert">{clearError}</p>}<div className="modal-actions"><button type="button" autoFocus disabled={clearing} onClick={()=>setConfirm(false)}>Cancel</button><button type="button" className="danger-button" disabled={clearing} onClick={clear}>{clearing?'Clearing…':'Permanently clear data'}</button></div></Modal>}
 </div>
}
