import {useAccount, AccountSwitcher, HeaderControls, useAccountViewState} from './AccountScope.jsx';
import React,{useEffect,useId,useState} from 'react';
import RangePicker,{rangePresets} from './components/RangePicker.jsx';
import Select from './components/Select.jsx';
import {presetRange} from './calendar.js';
import {groupPnl,cumulative,instrumentPnl,weekdayPnl,tickerSelection} from './statistics.js';
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);
function Bars({title,rows,currency,tone,onSelect,selected}) {
 const max=Math.max(1,...rows.map(r=>Math.abs(r.net)));
 return <section className="panel report-bars"><h2>{title}</h2>{!rows.length?<p className="subtle">No completed trades</p>:rows.map(r=>{
  const Row=onSelect?'button':'div';
  return <Row className={`report-bar-row${onSelect?' report-ticker-row':''}`} key={r.label} {...(onSelect?{type:'button',onClick:()=>onSelect(r.label),'aria-pressed':selected===r.label}: {})}><div><strong>{r.label}</strong><span className={r.net<0?'report-loss':'report-gain'}>{money(r.net,currency)}</span></div><div className="report-bar-track"><span style={{width:`${Math.abs(r.net)/max*100}%`,background:r.net<0?'var(--pnl-negative)':'var(--pnl-positive)'}}/></div><small>{r.count} {r.count===1?'trade':'trades'}</small></Row>
 })}</section>
}
function Curve({rows,start,end,currency}){
 const id=useId().replaceAll(':',''),[active,setActive]=useState(null),points=cumulative(rows,start,end);const values=[0,...points.map(p=>p.net)];let min=Math.min(...values),max=Math.max(...values);const pad=Math.max((max-min)*.12,1);min-=pad;max+=pad;const x=i=>70+(points.length===1?365:i/(points.length-1)*730),y=v=>300-(v-min)/(max-min)*260,zero=y(0);const line=points.map((p,i)=>i?`C ${(x(i-1)+x(i))/2} ${y(points[i-1].net)}, ${(x(i-1)+x(i))/2} ${y(p.net)}, ${x(i)} ${y(p.net)}`:`M ${x(i)} ${y(p.net)}`).join(' ');const area=points.length?`${line} L ${x(points.length-1)} ${zero} L ${x(0)} ${zero} Z`:'';
 return <section className="panel report-curve"><div className="panel-heading"><h2>Cumulative net P&amp;L</h2><strong className={(points.at(-1)?.net||0)<0?'report-loss':'report-gain'}>{money(points.at(-1)?.net||0,currency)}</strong></div>{!rows.length?<p className="empty">No completed trades in this timeframe.</p>:<><svg viewBox="0 0 840 350" role="img" aria-label="Cumulative net profit and loss by closing date"><defs><linearGradient id={`${id}gain`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--pnl-positive)" stopOpacity=".5"/><stop offset="1" stopColor="var(--pnl-positive)" stopOpacity=".04"/></linearGradient><linearGradient id={`${id}loss`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--pnl-negative)" stopOpacity=".04"/><stop offset="1" stopColor="var(--pnl-negative)" stopOpacity=".5"/></linearGradient><clipPath id={`${id}upper`}><rect x="65" y="0" width="740" height={zero}/></clipPath><clipPath id={`${id}lower`}><rect x="65" y={zero} width="740" height={350-zero}/></clipPath></defs>{Array.from({length:5},(_,i)=>{const v=min+(max-min)*i/4;return <g key={i}><line x1="70" x2="800" y1={y(v)} y2={y(v)} className="report-grid"/><text x="60" y={y(v)+4} textAnchor="end">{new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(v)}</text></g>})}<line x1="70" x2="800" y1={zero} y2={zero} className="report-zero"/>{['upper','lower'].map((part,i)=><g key={part} clipPath={`url(#${id}${part})`}><path d={area} fill={`url(#${id}${i?'loss':'gain'})`}/><path d={line} fill="none" stroke={i?'var(--pnl-negative)':'var(--pnl-positive)'} strokeWidth="3"/></g>)}{points.map((p,i)=><g key={p.label}><circle cx={x(i)} cy={y(p.net)} r={active===i?6:3} fill={p.net<0?'var(--pnl-negative)':'var(--pnl-positive)'} tabIndex="0" aria-label={`${p.label}: ${money(p.net,currency)}`} onFocus={()=>setActive(i)} onMouseEnter={()=>setActive(i)}><title>{p.label}: {money(p.net,currency)}</title></circle>{(i===0||i===points.length-1||(i<points.length-2&&i%Math.max(1,Math.ceil(points.length/5))===0))&&<text x={x(i)} y="330" textAnchor="middle">{p.label.slice(5)}</text>}</g>)}</svg><div className="report-chart-caption" role="status">{active!=null&&points[active]?`${points[active].label} · ${money(points[active].net,currency)}`:`${start} → ${end} · ${currency}`}</div></>}</section>
}
export default function Statistics({today}){
 const {scopedFetch}=useAccount();
 const [tab,setTab]=useState('P&L curve'),[period,setPeriod]=useAccountViewState('Statistics.jsx-period','current-month'),[custom,setCustom]=useAccountViewState('Statistics.jsx-custom',[today.slice(0,7)+'-01',today]),[picker,setPicker]=useState(false),[data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[currency,setCurrency]=useState('USD'),[search,setSearch]=useState(''),[selectedTicker,setSelectedTicker]=useState('');
 const [start,end]=period==='custom'?custom:presetRange(period,today);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');scopedFetch(`/api/statistics/?start=${start}&end=${end}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Could not load statistics.');return r.json()}).then(d=>{setData(d.rows);setCurrency(old=>d.rows.some(r=>r.currency===old)?old:d.rows[0]?.currency||'USD')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[start,end]);
 const currencies=[...new Set(data.map(r=>r.currency))].sort(),rows=data.filter(r=>r.currency===currency),tickers=groupPnl(rows,'ticker').sort((a,b)=>b.net-a.net||a.label.localeCompare(b.label)),hours=groupPnl(rows,'hour'),hourRows=Array.from({length:7},(_,i)=>{const h=i+9,r=hours.find(r=>r.label===String(h));return {label:`${h===9?'09:30':`${h}:00`}–${h+1}:00`,net:r?.net||0,count:r?.count||0}});if(hours.some(r=>r.label==='outside'))hourRows.push({...hours.find(r=>r.label==='outside'),label:'Outside regular hours'});
 const {matches,active}=tickerSelection(tickers,search,selectedTicker);
 const tickerRows=rows.filter(r=>r.ticker===active);
 const tickerProps={currency,onSelect:setSelectedTicker,selected:active};
 const tabs=['P&L curve','Tickers','Instruments','Time of day','Day of week','Strategies'];
 return <div className="statistics-view"><HeaderControls><div className="report-toolbar"><div><button className="date-picker-trigger" onClick={()=>setPicker(true)} aria-haspopup="dialog">{period==='custom'?'Custom range':rangePresets.find(p=>p[0]===period)?.[1]} <svg className="date-picker-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><small>{start} → {end}</small></div><AccountSwitcher/>{currencies.length>1&&<Select aria-label="Statistics currency" value={currency} onChange={e=>setCurrency(e.target.value)}>{currencies.map(c=><option key={c} value={c}>{c}</option>)}</Select>}</div></HeaderControls>{picker&&<RangePicker value={[start,end]} period={period} today={today} onClose={()=>setPicker(false)} onApply={(range,key)=>{setCustom(range);setPeriod(key);setPicker(false)}}/>}<div className="trade-detail-tabs" role="tablist" aria-label="Statistics reports">{tabs.map(name=><button key={name} role="tab" aria-selected={tab===name} tabIndex={tab===name?0:-1} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(tabs.indexOf(name)+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[index]);e.currentTarget.parentElement.children[index].focus()}}} onClick={()=>setTab(name)}>{name}</button>)}</div>{error?<p role="alert" className="alert error">{error}</p>:loading?<p role="status">Loading statistics…</p>:<div role="tabpanel" aria-label={tab}>{tab==='P&L curve'&&<Curve key={`${start}${end}${currency}`} rows={rows} start={start} end={end} currency={currency}/>} {tab==='Tickers'&&<><label className="report-search">Search ticker<input value={search} onChange={e=>{setSearch(e.target.value);setSelectedTicker('')}} placeholder="e.g. AMD"/></label>{search.trim()?<Bars title="Ticker search" rows={matches} {...tickerProps}/>:<div className="report-columns"><Bars title="Best 10 tickers" rows={tickers.slice(0,10)} {...tickerProps}/><Bars title="Worst 10 tickers" rows={tickers.slice().reverse().slice(0,10)} {...tickerProps}/></div>}{active?<Bars title={`${active} · P&L by instrument`} rows={instrumentPnl(tickerRows)} currency={currency} tone="var(--report-blue)"/>:<section className="panel report-bars"><h2>P&amp;L by instrument</h2><p className="subtle">Select a ticker</p></section>}</>}{tab==='Instruments'&&<Bars title="P&L by instrument" rows={instrumentPnl(rows)} currency={currency} tone="var(--report-blue)"/>}{tab==='Day of week'&&<Bars title="P&L by closing day" rows={weekdayPnl(rows)} currency={currency} tone="var(--report-violet)"/>}{tab==='Time of day'&&<Bars title="P&L by entry hour · New York time" rows={hourRows} currency={currency}/>} {tab==='Strategies'&&<Bars title="P&L by strategy" rows={groupPnl(rows,'strategy').sort((a,b)=>b.net-a.net)} currency={currency} tone="var(--report-violet)"/>}</div>}</div>
}
