import React,{useState} from 'react';
import Modal from './components/Modal.jsx';
import TradeDetails from './TradeDetails.jsx';
export default function StatTrades({drill,ledger,request,onUpdated,notify,csrfToken,onClose}){
 const [page,setPage]=useState(0),[selected,setSelected]=useState(null);
 const rows=ledger.trades.filter(t=>drill.ids.includes(t.trade_id)).sort((a,b)=>b.order_time.localeCompare(a.order_time));
 const pages=Math.max(1,Math.ceil(rows.length/5)),current=Math.min(page,pages-1);
 return <><Modal title={drill.title} onClose={onClose} className="stat-trades-modal"><div className="stat-trades-list"><div className="stat-trade-headers"><span>Open time</span><span>Ticker</span><span>Side</span><span>Net P&amp;L</span></div>{rows.slice(current*5,current*5+5).map(t=><button className="report-bar-row report-ticker-row stat-trade-row" key={t.trade_id} onClick={()=>setSelected(t)}><time>{t.order_time}</time><span className="ticker-pill">{t.symbol}</span><span>{t.direction}</span><strong className={Number(t.net)<0?'is-loss':Number(t.net)>0?'is-gain':'pnl-neutral'}>{new Intl.NumberFormat('en-US',{style:'currency',currency:t.currency}).format(t.net)}</strong></button>)}{!rows.length&&<p>No trades in this group.</p>}</div><nav className="stat-pagination" aria-label="Trade pages"><span className="stat-page-count" role="status">Page {current+1} of {pages} · {rows.length} trades</span><div className="stat-page-buttons"><button disabled={current===0} onClick={()=>setPage(current-1)} className="stat-page-arrow" aria-label="Previous page" title="Previous page"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 6-6 6 6 6"/></svg></button>{Array.from({length:pages},(_,index)=><button key={index} aria-label={`Page ${index+1}`} aria-current={current===index?'page':undefined} onClick={()=>setPage(index)}>{index+1}</button>)}<button disabled={current+1>=pages} onClick={()=>setPage(current+1)} className="stat-page-arrow" aria-label="Next page" title="Next page"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m10 6 6 6-6 6"/></svg></button></div></nav></Modal>{selected&&<TradeDetails trade={selected} executions={ledger.executions.filter(e=>selected.execution_ids?.includes(e.trade_id))} request={request} csrfToken={csrfToken} notify={notify} onClose={()=>setSelected(null)} onUpdated={async result=>{await onUpdated(result);setSelected(null);onClose()}}/>}</>;
}
