import {useAccount} from './AccountScope.jsx';
import React,{useEffect,useState,useRef} from 'react';
import Modal from './components/Modal.jsx';
import Select from './components/Select.jsx';
import Popover from './components/Popover.jsx';
const money=(value,currency)=>value==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(value));
function StrategyMenu({strategy,onEdit,onDelete}){
 const anchor=useRef(null),[open,setOpen]=useState(false);
 return <div onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><button ref={anchor} className="strategy-menu-trigger" aria-label={`Actions for ${strategy.name}`} aria-expanded={open} onClick={()=>setOpen(!open)}>⋮</button>{open&&<Popover anchor={anchor} label="Strategy actions" className="strategy-mini-menu" onClose={()=>setOpen(false)}><button onClick={()=>{setOpen(false);onEdit(strategy)}}>Edit</button><button className="is-loss" onClick={()=>{setOpen(false);onDelete(strategy)}}>Delete</button></Popover>}</div>
}
export default function Strategies({request,notify}){
 const {scopedFetch}=useAccount();
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[name,setName]=useState(''),[criteria,setCriteria]=useState(['']),[currency,setCurrency]=useState('USD'),[selected,setSelected]=useState(null),[editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null);
 function edit(s){setSelected(null);setEditing(s);setName(s.name);setCriteria(s.criteria.map(c=>({...c})));setError('');setCreating(true)}
 async function remove(){setSaving(true);setError('');try{await request(`/api/strategies/${deleting.id}/`,'DELETE');setItems(old=>old.filter(s=>s.id!==deleting.id));setSelected(null);setDeleting(null);notify('Strategy deleted.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 useEffect(()=>{const controller=new AbortController();scopedFetch('/api/strategies/',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Could not load strategies.');return r.json()}).then(d=>{setItems(d.strategies);const currencies=d.strategies.flatMap(s=>Object.keys(s.currencies));if(currencies.length&&!currencies.includes('USD'))setCurrency(currencies[0])}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>setLoading(false));return()=>controller.abort()},[]);
 const currencies=[...new Set(items.flatMap(s=>Object.keys(s.currencies)))].sort();
 const rows=items.map(s=>({...s,stats:s.currencies[currency]||{trades:0,closed:0}}));
 const ranked=rows.filter(s=>s.stats.closed>0).sort((a,b)=>Number(b.stats.net)-Number(a.stats.net));
 const active=rows.filter(s=>s.stats.trades>0).sort((a,b)=>b.stats.trades-a.stats.trades)[0];
 const win=ranked.slice().sort((a,b)=>b.stats.win_rate-a.stats.win_rate)[0];
 async function create(e){e.preventDefault();setSaving(true);setError('');try{const result=await request(editing?`/api/strategies/${editing.id}/`:'/api/strategies/',editing?'PUT':'POST',{name,criteria:editing?criteria:criteria.map(c=>c.text)});setItems(old=>editing?old.map(s=>s.id===editing.id?{...s,...result}:s):[...old,result]);setCreating(false);notify(editing?'Strategy updated.':'Strategy created.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="strategies-view"><div className="strategy-actions">{currencies.length>1&&<Select aria-label="Strategy currency" value={currency} onChange={e=>setCurrency(e.target.value)}>{currencies.map(c=><option key={c} value={c}>{c}</option>)}</Select>}<button className="primary" onClick={()=>{setEditing(null);setName('');setCriteria([{text:''}]);setError('');setCreating(true)}}>＋ Create strategy</button></div>
 {!creating&&error&&<p role="alert" className="alert error">{error}</p>}
 <div className="strategy-highlights">{[['Best performing strategy',ranked[0],'net'],['Least performing strategy',ranked.at(-1),'net'],['Most active strategy',active,'trades'],['Best win rate',win,'win_rate']].map(([label,s,key])=><section className="panel strategy-highlight" key={label}><span className="subtle">{label}</span><h3>{s?.name||'—'}</h3><strong className={key==='net'&&s?(Number(s.stats.net)<0?'is-loss':'is-gain'):''}>{!s?'—':key==='net'?money(s.stats.net,currency):key==='win_rate'?`${s.stats.win_rate}%`:`${s.stats.trades} ${s.stats.trades===1?'trade':'trades'}`}</strong></section>)}</div>
 <section className="panel strategy-list"><div className="panel-heading"><h2>Strategies</h2><span className="ticker-pill">{items.length}</span></div>{loading?<p role="status">Loading strategies…</p>:!items.length?<div className="empty">No strategies yet.</div>:<div className="strategy-table-scroll"><table className="strategy-table"><thead><tr>{['Strategy','Average winner','Average loser','Net P&L','Trades','Expectancy','Win rate',''].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id} tabIndex={0} onClick={()=>{setError('');setSelected(s)}} onKeyDown={e=>{if(e.target===e.currentTarget&&['Enter',' '].includes(e.key)){e.preventDefault();setSelected(s)}}}><td><button className="strategy-name" onClick={()=>setSelected(s)}>{s.name}</button><small>{s.criteria.length} criteria</small></td>{['average_winner','average_loser','net'].map(key=><td key={key} className={s.stats[key]!=null?(Number(s.stats[key])<0?'is-loss':'is-gain'):''}>{key==='net'&&!s.stats.closed?'—':money(s.stats[key],currency)}</td>)}<td>{s.stats.trades}</td><td>{money(s.stats.expectancy,currency)}</td><td>{s.stats.win_rate==null?'—':`${s.stats.win_rate}%`}</td><td><StrategyMenu strategy={s} onEdit={edit} onDelete={s=>{setError('');setDeleting(s)}}/></td></tr>)}</tbody></table></div>}</section>
 {creating&&<Modal title={editing?'Edit strategy':'Create strategy'} busy={saving} onClose={()=>setCreating(false)}><form className="strategy-form" onSubmit={create}><label>Strategy name<input autoFocus required maxLength={100} value={name} disabled={saving} onChange={e=>setName(e.target.value)}/></label><div className="strategy-criteria">{criteria.map((text,i)=><label key={i}>Criterion {i+1}<div className="strategy-criterion-input"><textarea required rows={2} maxLength={500} value={text.text} disabled={saving} onChange={e=>setCriteria(old=>old.map((v,n)=>n===i?{...v,text:e.target.value}:v))}/><button type="button" disabled={criteria.length===1||saving} aria-label={`Remove criterion ${i+1}`} onClick={()=>setCriteria(old=>old.filter((_,n)=>n!==i))}>×</button></div></label>)}</div><button type="button" disabled={criteria.length>=50||saving} onClick={()=>setCriteria(old=>[...old,{text:''}])}>＋ Add criterion</button>{error&&<p role="alert" className="alert error">{error}</p>}<button className="primary" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Create strategy'}</button></form></Modal>}
 {selected&&!deleting&&<Modal title={selected.name} onClose={()=>setSelected(null)}><ol className="strategy-definition">{selected.criteria.map(c=><li key={c.id}>{c.text}</li>)}</ol><div className="strategy-modal-actions"><button onClick={()=>edit(selected)}>Edit</button><button className="is-loss" onClick={()=>{setError('');setDeleting(selected)}}>Delete</button></div></Modal>}
 {deleting&&<Modal title="Delete strategy?" busy={saving} onClose={()=>{setDeleting(null);setError('')}}><p>Delete “{deleting.name}” and its criteria? It will be unlinked from all trades. Your trades, notes, and attachments will remain. This cannot be undone.</p>{error&&<p className="alert error" role="alert">{error}</p>}<div className="strategy-modal-actions"><button disabled={saving} onClick={()=>{setDeleting(null);setError('')}}>Cancel</button><button disabled={saving} className="is-loss" onClick={remove}>{saving?'Deleting…':'Delete strategy'}</button></div></Modal>}
 </div>
}
