import React, {useEffect,useState} from 'react';
import ManualTradeForm from './ManualTradeForm.jsx';
import TradeDetails from './TradeDetails.jsx';
import Select from './components/Select.jsx';
const money=v=>Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const columns=[['order_time','Time'],['symbol','Ticker'],['direction','Side'],['instrument','Instrument'],['quantity','Qty'],['price','Avg entry'],['net','Net P&L'],['gross','Gross P&L']];
const instrument=r=>r.asset_class==='OPT'?`${r.expiry} · ${Number(r.strike)} ${r.put_call==='C'?'Call':'Put'}`:r.asset_class==='FUT'?'Future':'Stock';
const currencyMoney=(value,currency)=>{try{return new Intl.NumberFormat('en-US',{style:'currency',currency,minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value))}catch{return `${money(value)} ${currency}`}};
function executionCell(r,key){
 if(key==='symbol')return <span className="ticker-pill">{r.symbol}</span>;
 if(key==='order_time')return <time dateTime={r.order_time.replace(' ','T')}>{r.order_time.slice(11)}</time>;
 if(key==='instrument')return <span className="instrument-label">{instrument(r)}</span>;
 if(key==='direction')return <span className="side-label">{r.direction}</span>;
 if(key==='net'||key==='gross'){if(r.is_open)return <span className="pnl-pending">(Open)</span>;if(r[key]===null)return <span className="pnl-incomplete" title="Import the missing opening fills to calculate P&L">Incomplete</span>;return <span className={`execution-pnl ${Number(r[key])<0?'is-loss':Number(r[key])>0?'is-gain':''}`} title={r.currency}>{currencyMoney(r[key],r.currency)}</span>}
 if(key==='price'&&r.price===null)return '—';
 if(key==='price')return <span title={r.currency}>{currencyMoney(r.price,r.currency)}</span>;
 return Number(r[key]).toLocaleString('en-US',{maximumFractionDigits:8});
}
const numeric=new Set(['quantity','price','gross','net','commission','multiplier','strike']);
export default function TradeJournal({day,change,ledger,request,onUpdated,notify,csrfToken}){
 const [mode,setMode]=useState('CSV import'),[asset,setAsset]=useState('STK'),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sort,setSort]=useState(['order_time',1]),[selected,setSelected]=useState(null);
 const [accounts,setAccounts]=useState([]),[accountId,setAccountId]=useState(''),[accountsReady,setAccountsReady]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch('/api/accounts/',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Could not load brokerage accounts.');return r.json()}).then(d=>{setAccounts(d.accounts);setAccountId(d.accounts.length===1?String(d.accounts[0].id):'');setAccountsReady(true)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[]);
 const importAccount=accountId?Number(accountId):undefined;
 const rows=(ledger.trades||[]).filter(r=>r.sessions.includes(day.date)).sort((a,b)=>{const [key,d]=sort;return d*(numeric.has(key)?Number(a[key])-Number(b[key]):String(key==='instrument'?instrument(a):a[key]??'').localeCompare(String(key==='instrument'?instrument(b):b[key]??'')))||a.execution_time.localeCompare(b.execution_time)||a.trade_id.localeCompare(b.trade_id)});
 async function perform(body){setBusy(true);setError('');try{const result=await request('/api/executions/','POST',body);await onUpdated(result,body.csv?preview?.dates:undefined);notify(`Saved ${result.imported} execution${result.imported===1?'':'s'} · ${result.duplicates} duplicates skipped.`);return true}catch(e){setError(e.message);return false}finally{setBusy(false)}}
 async function read(e){const file=e.target.files[0];e.target.value='';if(!file)return;setBusy(true);setError('');setPreview(null);try{if(file.size>2*1024*1024)throw Error('Choose a CSV up to 2 MB.');const csv=await file.text();const result=await request('/api/executions/','POST',{csv,preview:true,account_id:importAccount});setPreview({...result,csv,account_id:importAccount,name:file.name})}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel trade-journal"><div className="panel-heading"><h2><span className="step">03</span> Trade journal</h2></div>
 <div className="trade-modes" role="group" aria-label="Trade entry mode">{['Broker sync','CSV import','Manual'].map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div>
 {mode==='Manual'&&<div className="trade-modes instrument-tabs" role="group" aria-label="Manual instrument type">{[['STK','Stock'],['OPT','Option'],['FUT','Future']].map(([value,label])=><button key={value} type="button" aria-pressed={asset===value} disabled={busy} onClick={()=>setAsset(value)}>{label}</button>)}</div>}
 {error&&<p className="alert error" role="alert">{error}</p>}<div className="trade-entry">
 {mode==='Broker sync'&&<p>Automatic broker sync is coming later. Import a CSV or add executions manually below.</p>}
 {mode==='CSV import'&&<>{accounts.length>0&&<label className="import-account">Brokerage account<Select disabled={busy} value={accountId} onChange={e=>{setAccountId(e.target.value);setPreview(null);setError('')}}><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.broker_name}</option>)}</Select></label>}<label className="attachment-upload">Choose execution CSV<input type="file" accept=".csv,text/csv" disabled={busy||!accountsReady||(accounts.length>0&&!accountId)} onChange={read}/></label>{preview&&<div className="csv-preview"><h3>{preview.rows.length} new executions · {preview.duplicates} duplicates</h3><p>{preview.name}</p>{preview.warnings?.map(w=><p key={w} role="status">{w}</p>)}<p>Sessions: {preview.dates.join(', ')||'Already imported'}</p><button disabled={busy} className="primary" onClick={async()=>{if(await perform({csv:preview.csv,account_id:preview.account_id}))setPreview(null)}}>{busy?'Importing…':preview.rows.length?'Import executions':'View imported executions'}</button></div>}</>}
 {mode==='Manual'&&<ManualTradeForm key={`${day.date}-${asset}`} asset={asset} date={day.date} request={request} onUpdated={onUpdated} notify={notify}/>}
 </div><div className="trade-list-section"><div className="session-trades-heading"><h3>Session trades <small className="subtle">{day.date}</small></h3><div className="session-trades-summary">{Object.entries(ledger.summaries[day.date]||{}).map(([currency,s])=><div className="session-net" key={currency}><span className="session-net-label">Net P&L</span><strong className={`execution-pnl ${Number(s.net)<0?'is-loss':Number(s.net)>0?'is-gain':''}`}>{currencyMoney(s.net,currency)}</strong>{s.incomplete>0&&<small className="pnl-incomplete">Incomplete</small>}</div>)}<span className="session-trade-count">{rows.length} {rows.length===1?'trade':'trades'}</span></div></div>
 {!rows.length?<p className="attachment-empty">No trades for this session yet.</p>:<div className="execution-table-wrap"><table className="execution-table"><thead><tr>{columns.map(([key,label])=><th key={key} aria-sort={sort[0]===key?(sort[1]===1?'ascending':'descending'):'none'}><button onClick={()=>setSort([key,sort[0]===key?-sort[1]:1])}>{label}{sort[0]===key?(sort[1]===1?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.trade_id} tabIndex={0} aria-label={`View ${r.symbol} trade opened ${r.order_time}`} onClick={()=>setSelected(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r)}}}>{columns.map(([key])=><td key={key} className={['net','gross','price','quantity'].includes(key)?'numeric-cell':''}>{executionCell(r,key)}</td>)}</tr>)}</tbody></table></div>}
 {!!day.trades.length&&<><h3>Previously entered trades</h3><p className="footnote">These saved P&L entries remain separate from the execution ledger.</p><ul className="trade-list">{day.trades.map((t,i)=><li className="trade-list-row" key={i}><strong>{t.symbol}</strong><span>{t.side}</span><span>{money(t.pnl)}</span><button aria-label={`Remove ${t.symbol}`} onClick={()=>change({trades:day.trades.filter((_,j)=>j!==i)})}>×</button></li>)}</ul></>}
 </div>{selected&&<TradeDetails trade={selected} executions={ledger.executions.filter(r=>selected.execution_ids?.includes(r.trade_id))} onUpdated={async result=>{await onUpdated(result);setSelected(null)}} request={request} csrfToken={csrfToken} notify={notify} onClose={()=>setSelected(null)}/>}</section>
}
