import React, {useRef,useState} from 'react';
import Select from './components/Select.jsx';
import {parseTradeCsv} from './tradeCsv.js';
const money=value=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value));
export default function TradeJournal({day,trade,changeTrade,addTrade,change}) {
 const [mode,setMode]=useState('Manual'),[preview,setPreview]=useState(null),[error,setError]=useState(''),[reading,setReading]=useState(false);const generation=useRef(0);
 async function readCsv(event){
  const file=event.target.files[0];event.target.value='';if(!file)return;
  const run=++generation.current;setPreview(null);setError('');setReading(true);
  try{if(file.size>2*1024*1024)throw Error('Choose a CSV file up to 2 MB.');const trades=parseTradeCsv(await file.text(),day.date);if(run===generation.current)setPreview({name:file.name,trades})}catch(e){setError(e.message)}finally{setReading(false)}
 }
 function commit(){if(day.trades.length+preview.trades.length>500){setError('A day can contain at most 500 trades.');return}change({trades:[...day.trades,...preview.trades]});setPreview(null);setError('')}
 return <section className="panel trade-journal"><div className="panel-heading"><h2><span className="step">03</span> Trade journal</h2><span className="subtle">{day.trades.length} entries</span></div>
 <div className="trade-modes" role="group" aria-label="Trade entry mode">{['Broker sync','CSV import','Manual'].map(name=><button key={name} type="button" aria-pressed={mode===name} onClick={()=>setMode(name)}>{name}</button>)}</div>
 <div className="trade-entry">
 {mode==='Broker sync'&&<div className="broker-placeholder"><span className="subtle">Coming later</span><h3>Connect your broker</h3><p>Automatic trade imports will be available here when broker sync is added. Use CSV import or Manual for now.</p><button disabled>Broker sync unavailable</button></div>}
 {mode==='CSV import'&&<div><label className="attachment-upload">Import trades for {day.date}<input type="file" accept=".csv,text/csv" onChange={readCsv} disabled={reading}/></label><p className="footnote">Columns: symbol, side (Long/Short), pnl. Optional: notes, date (YYYY-MM-DD). Imports append to this day; duplicate trades are not automatically removed.</p><details><summary>Example CSV</summary><pre>{'symbol,side,pnl,notes\nAAPL,Long,125.50,Planned breakout\nMSFT,Short,-40.00,Stopped out'}</pre></details>{reading&&<p role="status">Reading CSV…</p>}{error&&<p className="alert error" role="alert">{error}</p>}{preview&&<div className="csv-preview"><h3>{preview.trades.length} trades ready to add</h3><p>{preview.name} · Net P&L {money(preview.trades.reduce((n,t)=>n+Number(t.pnl),0))}</p><ul>{preview.trades.slice(0,5).map((t,i)=><li key={i}>{t.symbol} · {t.side} · {money(t.pnl)}</li>)}</ul>{preview.trades.length>5&&<small>And {preview.trades.length-5} more trades.</small>}<div className="modal-actions"><button onClick={()=>setPreview(null)}>Cancel import</button><button className="primary" onClick={commit}>Add {preview.trades.length} trades</button></div></div>}</div>}
 {mode==='Manual'&&<form onSubmit={addTrade} className="trade-form"><label>Symbol<input required maxLength="30" placeholder="e.g. ES" value={trade.symbol} onChange={e=>changeTrade({...trade,symbol:e.target.value})}/></label><label>Side<Select value={trade.side} onChange={e=>changeTrade({...trade,side:e.target.value})}><option>Long</option><option>Short</option></Select></label><label>Net P&L<input required type="number" step="0.01" min="-999999999" max="999999999" placeholder="0.00" value={trade.pnl} onChange={e=>changeTrade({...trade,pnl:e.target.value})}/></label><label className="trade-notes">Trade notes<input maxLength="2000" placeholder="Setup, execution, or lesson…" value={trade.notes} onChange={e=>changeTrade({...trade,notes:e.target.value})}/></label><button type="submit" disabled={day.trades.length>=500}>+ Add trade</button></form>}
 </div>
 <div className="trade-list-section"><h3>Session trades</h3>{!day.trades.length?<p className="attachment-empty">No trades added for this day yet.</p>:<><div className="trade-list-labels" aria-hidden="true"><span>Ticker</span><span>Side</span><span>Net P&L</span><span/></div><ul className="trade-list">{day.trades.map((t,i)=><li key={i} className="trade-list-row"><strong>{t.symbol}</strong><span>{t.side}</span><span className={Number(t.pnl)<0?'negative':'positive'}>{money(t.pnl)}</span><button className="text-button" aria-label={`Remove ${t.symbol} trade ${i+1}`} onClick={()=>change({trades:day.trades.filter((_,j)=>i!==j)})}>×</button>{t.notes&&<small className="trade-row-notes">{t.notes}</small>}</li>)}</ul></>}</div>
 </section>;
}
