# Generated by Django 5.2.17 on 2026-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('plan', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True)),
                ('checks', models.JSONField(default=list)),
                ('trades', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
