# Generated by Django 5.2.17 on 2026-09-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='draft_trade',
            field=models.JSONField(default=dict),
        ),
    ]
