# Generated by Django 5.2.17 on 2026-09-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_day_draft_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
