# Generated by Django 5.2.17 on 2026-09-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=100, unique=True)),
                ('session_date', models.DateField(db_index=True)),
                ('execution_time', models.CharField(db_index=True, max_length=30)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
