# Generated by Django 5.2.17 on 2026-09-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReview',
            fields=[
                ('trade_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='trade_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
