# Generated by Django 5.2.17 on 2026-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_tradereview_attachment_trade_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFileDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
