# Generated by Django 5.2.17 on 2026-09-23 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0006_pendingfiledeletion_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("criteria", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradeStrategy",
            fields=[
                ("trade_key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("checked", models.JSONField(default=list)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="journal.strategy"
                    ),
                ),
            ],
        ),
    ]
