# Generated by Django 5.2.17 on 2026-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_strategy_tradestrategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerageAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "broker",
                    models.CharField(
                        choices=[("ibkr", "Interactive Brokers"), ("schwab", "Charles Schwab")],
                        max_length=20,
                    ),
                ),
                ("source_identifier", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_import_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
