# Generated by Django 5.2.17 on 2026-09-24 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0008_brokerageaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="journal.brokerageaccount",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="journal.brokerageaccount",
            ),
        ),
        migrations.AddField(
            model_name="execution",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="journal.brokerageaccount",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(
                fields=("account", "date"), name="unique_account_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", True)),
                fields=("date",),
                name="unique_unassigned_day",
            ),
        ),
    ]
