# Generated by Django 5.2.17 on 2026-09-24 23:39

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("journal", "0010_assign_existing_accounts"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="pendingfiledeletion",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.brokerageaccount",
            ),
        ),
    ]
