# Generated by Django 5.2.17 on 2026-09-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0011_pendingfiledeletion_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerageaccount",
            name="broker",
            field=models.CharField(
                choices=[
                    ("ibkr", "Interactive Brokers"),
                    ("schwab", "Charles Schwab"),
                    ("tradovate", "Tradovate"),
                ],
                max_length=20,
            ),
        ),
    ]
