# Generated by Django 5.2.17 on 2026-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_brokerageaccount_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, upload_to='profiles/'),
        ),
    ]
