# Generated by Django 5.2.17 on 2026-10-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0013_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(default="idle", max_length=20)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("last_attempt", models.DateTimeField(null=True)),
                ("last_success", models.DateTimeField(null=True)),
                ("last_report_date", models.DateField(null=True)),
                ("scheduled_day", models.DateField(null=True)),
                ("retry_at", models.DateTimeField(null=True)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("lease_until", models.DateTimeField(null=True)),
                ("run_id", models.CharField(blank=True, max_length=40)),
                ("requested", models.BooleanField(default=False)),
                ("imported", models.PositiveIntegerField(default=0)),
                ("duplicates", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="journal.brokerageaccount",
                    ),
                ),
            ],
        ),
    ]
