# Generated by Django 5.2.17 on 2026-10-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_rule_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokersync',
            name='conflicts',
            field=models.JSONField(default=list),
        ),
    ]
